name: Merge and Clean HTML Comments

on:
  pull_request:
    branches:
      - test 1  # Trigger on pull requests to the "test 1" branch
    paths: # Optional: Trigger on changes to specific paths
      - '**.html' # Only trigger on HTML files, adjust as needed

jobs:
  merge_and_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the PR branch

      - name: Merge test 1 branch
        run: git merge test 1

      - name: Remove HTML comments (if from test 2 branch)
        if: github.event.pull_request.head.ref == 'test 2'
        run: |
          find. -type f -name "*.html" -print0 | xargs -0 -I {} perl -0777 -pe 's///sg' {}

      - name: Commit changes (if comments were removed)
        if: github.event.pull_request.head.ref == 'test 2'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add.
          git commit -m "Removed HTML comments" || true

      - name: Push changes (if comments were removed)
        if: github.event.pull_request.head.ref == 'test 2'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }} # Push back to the PR branch
